name: socket_io
description: >
  Port of JS/Node library Socket.io. It enables real-time, bidirectional and 
  event-based communication cross-platform.
version: 1.0.1
homepage: https://www.zkoss.org
repository: https://github.com/rikulo/socket.io-dart
issue_tracker: https://github.com/rikulo/socket.io-dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  stream: ^3.0.3
  socket_io_common: ^1.0.1
  uuid: ^4.2.1
  logging: ^1.2.0
dev_dependencies:
  test: ^1.24.9
  lints: ^3.0.0
